openapi: 3.0.1
info:
  title: Twilio - Api
  description: This is the public Twilio REST API.
  termsOfService: https://www.twilio.com/legal/tos
  contact:
    name: Twilio Support
    url: https://support.twilio.com
    email: support@twilio.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
components:
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
  schemas:
    api.v2010.account.message:
      type: object
      properties:
        body:
          type: string
          nullable: true
          description: The text content of the message
          x-twilio:
            pii:
              handling: standard
              deleteSla: 30
        num_segments:
          type: string
          nullable: true
          description: 'The number of segments that make up the complete message.
            SMS message bodies that exceed the [character limit](https://www.twilio.com/docs/glossary/what-sms-character-limit)
            are segmented and charged as multiple messages. Note: For messages sent
            via a Messaging Service, `num_segments` is initially `0`, since a sender
            hasn''t yet been assigned.'
        direction:
          type: string
          $ref: '#/components/schemas/message_enum_direction'
          nullable: true
          description: 'The direction of the message. Can be: `inbound` for incoming
            messages, `outbound-api` for messages created by the REST API, `outbound-call`
            for messages created during a call, or `outbound-reply` for messages created
            in response to an incoming message.'
        from:
          type: string
          format: phone-number
          nullable: true
          description: The sender's phone number (in [E.164](https://en.wikipedia.org/wiki/E.164)
            format), [alphanumeric sender ID](https://www.twilio.com/docs/sms/quickstart),
            [Wireless SIM](https://www.twilio.com/docs/iot/wireless/programmable-wireless-send-machine-machine-sms-commands),
            [short code](https://www.twilio.com/en-us/messaging/channels/sms/short-codes),
            or  [channel address](https://www.twilio.com/docs/messaging/channels)
            (e.g., `whatsapp:+15554449999`). For incoming messages, this is the number
            or channel address of the sender. For outgoing messages, this value is
            a Twilio phone number, alphanumeric sender ID, short code, or channel
            address from which the message is sent.
          x-twilio:
            pii:
              handling: standard
              deleteSla: 120
        to:
          type: string
          nullable: true
          description: The recipient's phone number (in [E.164](https://en.wikipedia.org/wiki/E.164)
            format) or [channel address](https://www.twilio.com/docs/messaging/channels)
            (e.g. `whatsapp:+15552229999`)
          x-twilio:
            pii:
              handling: standard
              deleteSla: 120
        date_updated:
          type: string
          format: date-time-rfc-2822
          nullable: true
          description: The [RFC 2822](https://datatracker.ietf.org/doc/html/rfc2822#section-3.3)
            timestamp (in GMT) of when the Message resource was last updated
        price:
          type: string
          nullable: true
          description: The amount billed for the message in the currency specified
            by `price_unit`. The `price` is populated after the message has been sent/received,
            and may not be immediately availalble. View the [Pricing page](https://www.twilio.com/en-us/pricing)
            for more details.
        error_message:
          type: string
          nullable: true
          description: The description of the `error_code` if the Message `status`
            is `failed` or `undelivered`. If no error was encountered, the value is
            `null`. The value returned in this field for a specific error cause is
            subject to change as Twilio improves errors. Users should not use the
            `error_code` and `error_message` fields programmatically.
        uri:
          type: string
          nullable: true
          description: The URI of the Message resource, relative to `https://api.twilio.com`.
        account_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the [Account](https://www.twilio.com/docs/iam/api/account)
            associated with the Message resource
        num_media:
          type: string
          nullable: true
          description: The number of media files associated with the Message resource.
        status:
          type: string
          $ref: '#/components/schemas/message_enum_status'
          nullable: true
          description: 'The status of the Message. Possible values: `accepted`, `scheduled`,
            `canceled`, `queued`, `sending`, `sent`, `failed`, `delivered`, `undelivered`,
            `receiving`, `received`, or `read` (WhatsApp only). For more information,
            See [detailed descriptions](https://www.twilio.com/docs/sms/api/message-resource#message-status-values).'
        messaging_service_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^MG[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource)
            associated with the Message resource. A unique default value is assigned
            if a Messaging Service is not used.
        sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^(SM|MM)[0-9a-fA-F]{32}$
          nullable: true
          description: The unique, Twilio-provided string that identifies the Message
            resource.
        date_sent:
          type: string
          format: date-time-rfc-2822
          nullable: true
          description: The [RFC 2822](https://datatracker.ietf.org/doc/html/rfc2822#section-3.3)
            timestamp (in GMT) of when the Message was sent. For an outgoing message,
            this is when Twilio sent the message. For an incoming message, this is
            when Twilio sent the HTTP request to your incoming message webhook URL.
        date_created:
          type: string
          format: date-time-rfc-2822
          nullable: true
          description: The [RFC 2822](https://datatracker.ietf.org/doc/html/rfc2822#section-3.3)
            timestamp (in GMT) of when the Message resource was created
        error_code:
          type: integer
          nullable: true
          description: The [error code](https://www.twilio.com/docs/api/errors) returned
            if the Message `status` is `failed` or `undelivered`. If no error was
            encountered, the value is `null`. The value returned in this field for
            a specific error cause is subject to change as Twilio improves errors.
            Users should not use the `error_code` and `error_message` fields programmatically.
        price_unit:
          type: string
          format: currency
          nullable: true
          description: The currency in which `price` is measured, in [ISO 4127](https://www.iso.org/iso/home/standards/currency_codes.htm)
            format (e.g. `usd`, `eur`, `jpy`).
        api_version:
          type: string
          nullable: true
          description: The API version used to process the Message
        subresource_uris:
          type: object
          format: uri-map
          nullable: true
          description: A list of related resources identified by their URIs relative
            to `https://api.twilio.com`
    message_enum_status:
      type: string
      enum:
      - queued
      - sending
      - sent
      - failed
      - delivered
      - undelivered
      - receiving
      - received
      - accepted
      - scheduled
      - read
      - partially_delivered
      - canceled
    message_enum_update_status:
      type: string
      enum:
      - canceled
    message_enum_direction:
      type: string
      enum:
      - inbound
      - outbound-api
      - outbound-call
      - outbound-reply
    message_enum_content_retention:
      type: string
      enum:
      - retain
      - discard
    message_enum_address_retention:
      type: string
      enum:
      - retain
      - obfuscate
    message_enum_traffic_type:
      type: string
      enum:
      - free
    message_enum_schedule_type:
      type: string
      enum:
      - fixed
    message_enum_risk_check:
      type: string
      enum:
      - enable
      - disable
    api.v2010.account.message.message_feedback:
      type: object
      properties:
        account_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the [Account](https://www.twilio.com/docs/iam/api/account)
            associated with this MessageFeedback resource.
        message_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^(SM|MM)[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the Message resource associated with this MessageFeedback
            resource.
        outcome:
          type: string
          $ref: '#/components/schemas/message_feedback_enum_outcome'
          nullable: true
          description: 'Reported outcome indicating whether there is confirmation
            that the Message recipient performed a tracked user action. Can be: `unconfirmed`
            or `confirmed`. For more details see [How to Optimize Message Deliverability
            with Message Feedback](https://www.twilio.com/docs/messaging/guides/send-message-feedback-to-twilio).'
        date_created:
          type: string
          format: date-time-rfc-2822
          nullable: true
          description: The date and time in GMT when this MessageFeedback resource
            was created, specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt)
            format.
        date_updated:
          type: string
          format: date-time-rfc-2822
          nullable: true
          description: The date and time in GMT when this MessageFeedback resource
            was last updated, specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt)
            format.
        uri:
          type: string
          nullable: true
          description: The URI of the resource, relative to `https://api.twilio.com`.
    message_feedback_enum_outcome:
      type: string
      enum:
      - confirmed
      - unconfirmed
paths:
  /2010-04-01/Accounts/{AccountSid}/Messages.json:
    servers:
    - url: https://api.twilio.com
    description: A Message resource represents an inbound or outbound message.
    x-twilio:
      defaultOutputProperties:
      - sid
      - from
      - to
      - status
      - direction
      - date_sent
      dependentProperties:
        media:
          mapping:
            account_sid: account_sid
            message_sid: sid
          resource_url: /2010-04-01/Accounts/{account_sid}/Messages/{message_sid}/Media.json
        feedback:
          mapping:
            account_sid: account_sid
            message_sid: sid
          resource_url: /2010-04-01/Accounts/{account_sid}/Messages/{message_sid}/Feedback.json
      parent: /Accounts/{Sid}.json
      pathType: list
    post:
      description: Send a message
      tags:
      - Api20100401Message
      parameters:
      - name: AccountSid
        in: path
        description: The SID of the [Account](https://www.twilio.com/docs/iam/api/account)
          creating the Message resource.
        schema:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.v2010.account.message'
              examples:
                create:
                  value:
                    account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    api_version: '2010-04-01'
                    body: "Hello! \U0001F44D"
                    date_created: Thu, 24 Aug 2023 05:01:45 +0000
                    date_sent: Thu, 24 Aug 2023 05:01:45 +0000
                    date_updated: Thu, 24 Aug 2023 05:01:45 +0000
                    direction: outbound-api
                    error_code: null
                    error_message: null
                    from: '+14155552345'
                    num_media: '0'
                    num_segments: '1'
                    price: null
                    price_unit: null
                    messaging_service_sid: MGaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    sid: SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    status: queued
                    subresource_uris:
                      media: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Media.json
                    tags:
                      campaign_name: Spring Sale 2022
                      message_type: cart_abandoned
                    to: '+14155552345'
                    uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.json
                createWoService:
                  value:
                    account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    api_version: '2010-04-01'
                    body: "Hello! \U0001F44D"
                    date_created: Thu, 30 Jul 2015 20:12:31 +0000
                    date_sent: Thu, 30 Jul 2015 20:12:33 +0000
                    date_updated: Thu, 30 Jul 2015 20:12:33 +0000
                    direction: outbound-api
                    error_code: null
                    error_message: null
                    from: '+14155552345'
                    messaging_service_sid: MGaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    num_media: '0'
                    num_segments: '1'
                    price: null
                    price_unit: null
                    sid: SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    status: queued
                    subresource_uris:
                      media: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Media.json
                    tags: null
                    to: '+14155552345'
                    uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.json
                createWithMessagingService:
                  value:
                    account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    api_version: '2010-04-01'
                    body: "Hello! \U0001F44D"
                    date_created: Thu, 30 Jul 2015 20:12:31 +0000
                    date_sent: Thu, 30 Jul 2015 20:12:33 +0000
                    date_updated: Thu, 30 Jul 2015 20:12:33 +0000
                    direction: outbound-api
                    error_code: null
                    error_message: null
                    from: null
                    messaging_service_sid: MGaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    num_media: '0'
                    num_segments: '1'
                    price: null
                    price_unit: null
                    sid: SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    status: queued
                    subresource_uris:
                      media: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Media.json
                    tags: null
                    to: '+14155552345'
                    uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.json
                createWithQueuedStatus:
                  value:
                    account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    api_version: '2010-04-01'
                    body: "Hello! \U0001F44D"
                    date_created: Thu, 30 Jul 2015 20:12:31 +0000
                    date_sent: Thu, 30 Jul 2015 20:12:33 +0000
                    date_updated: Thu, 30 Jul 2015 20:12:33 +0000
                    direction: outbound-api
                    error_code: null
                    error_message: null
                    from: '+14155552345'
                    messaging_service_sid: MGaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    num_media: '0'
                    num_segments: '1'
                    price: null
                    price_unit: null
                    sid: SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    status: queued
                    subresource_uris:
                      media: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Media.json
                    tags: null
                    to: '+14155552345'
                    uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.json
                createScheduledMessageSms:
                  value:
                    account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    api_version: '2010-04-01'
                    body: "Hello! \U0001F44D"
                    date_created: Mon, 29 Nov 2021 22:40:10 +0000
                    date_sent: null
                    date_updated: Mon, 29 Nov 2021 22:40:10 +0000
                    direction: outbound-api
                    error_code: null
                    error_message: null
                    from: null
                    messaging_service_sid: MGaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    num_media: '0'
                    num_segments: '0'
                    price: null
                    price_unit: null
                    sid: SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    status: queued
                    subresource_uris:
                      media: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Media.json
                    tags: null
                    to: '+15558675310'
                    uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.json
                createScheduledMessageMms:
                  value:
                    account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    api_version: '2010-04-01'
                    body: "Hello! \U0001F44D"
                    date_created: Mon, 29 Nov 2021 22:40:10 +0000
                    date_sent: null
                    date_updated: Mon, 29 Nov 2021 22:40:10 +0000
                    direction: outbound-api
                    error_code: null
                    error_message: null
                    from: null
                    messaging_service_sid: MGaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    num_media: '1'
                    num_segments: '1'
                    price: null
                    price_unit: null
                    sid: MMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    status: accepted
                    subresource_uris:
                      media: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/MMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Media.json
                    tags: null
                    to: '+15558675310'
                    uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/MMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.json
                createScheduledMessageWhatsapp:
                  value:
                    account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    api_version: '2010-04-01'
                    body: "Hello! \U0001F44D"
                    date_created: Mon, 29 Nov 2021 22:40:10 +0000
                    date_sent: null
                    date_updated: Mon, 29 Nov 2021 22:40:10 +0000
                    direction: outbound-api
                    error_code: null
                    error_message: null
                    from: null
                    messaging_service_sid: MGaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    num_media: '0'
                    num_segments: '0'
                    price: null
                    price_unit: null
                    sid: SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    status: scheduled
                    subresource_uris:
                      media: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Media.json
                    tags: null
                    to: whatsapp:+15558675310
                    uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/SMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.json
          headers:
            Access-Control-Allow-Origin:
              description: Specify the origin(s) allowed to access the resource
              schema:
                type: string
              example: '*'
            Access-Control-Allow-Methods:
              description: Specify the HTTP methods allowed when accessing the resource
              schema:
                type: string
              example: POST, OPTIONS
            Access-Control-Allow-Headers:
              description: Specify the headers allowed when accessing the resource
              schema:
                type: string
              example: Content-Type, Authorization
            Access-Control-Allow-Credentials:
              description: Indicates whether the browser should include credentials
              schema:
                type: boolean
            Access-Control-Expose-Headers:
              description: Headers exposed to the client
              schema:
                type: string
                example: X-Custom-Header1, X-Custom-Header2
          description: Created
      security:
      - accountSid_authToken: []
      operationId: CreateMessage
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              title: CreateMessageRequest
              properties:
                To:
                  type: string
                  format: phone-number
                  description: The recipient's phone number in [E.164](https://www.twilio.com/docs/glossary/what-e164)
                    format (for SMS/MMS) or [channel address](https://www.twilio.com/docs/messaging/channels),
                    e.g. `whatsapp:+15552229999`.
                StatusCallback:
                  type: string
                  format: uri
                  description: 'The URL of the endpoint to which Twilio sends [Message
                    status callback requests](https://www.twilio.com/docs/sms/api/message-resource#twilios-request-to-the-statuscallback-url).
                    URL must contain a valid hostname and underscores are not allowed.
                    If you include this parameter with the `messaging_service_sid`,
                    Twilio uses this URL instead of the Status Callback URL of the
                    [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource). '
                ApplicationSid:
                  type: string
                  minLength: 34
                  maxLength: 34
                  pattern: ^AP[0-9a-fA-F]{32}$
                  description: The SID of the associated [TwiML Application](https://www.twilio.com/docs/usage/api/applications).
                    [Message status callback requests](https://www.twilio.com/docs/sms/api/message-resource#twilios-request-to-the-statuscallback-url)
                    are sent to the TwiML App's `message_status_callback` URL. Note
                    that the `status_callback` parameter of a request takes priority
                    over the `application_sid` parameter; if both are included `application_sid`
                    is ignored.
                MaxPrice:
                  type: number
                  description: '[OBSOLETE] This parameter will no longer have any
                    effect as of 2024-06-03.'
                ProvideFeedback:
                  type: boolean
                  description: Boolean indicating whether or not you intend to provide
                    delivery confirmation feedback to Twilio (used in conjunction
                    with the [Message Feedback subresource](https://www.twilio.com/docs/sms/api/message-feedback-resource)).
                    Default value is `false`.
                Attempt:
                  type: integer
                  description: Total number of attempts made (including this request)
                    to send the message regardless of the provider used
                ValidityPeriod:
                  type: integer
                  description: The maximum length in seconds that the Message can
                    remain in Twilio's outgoing message queue. If a queued Message
                    exceeds the `validity_period`, the Message is not sent. Accepted
                    values are integers from `1` to `36000`. Default value is `36000`.
                    A `validity_period` greater than `5` is recommended. [Learn more
                    about the validity period](https://www.twilio.com/blog/take-more-control-of-outbound-messages-using-validity-period-html)
                ForceDelivery:
                  type: boolean
                  description: Reserved
                ContentRetention:
                  type: string
                  $ref: '#/components/schemas/message_enum_content_retention'
                  description: Determines if the message content can be stored or
                    redacted based on privacy settings
                AddressRetention:
                  type: string
                  $ref: '#/components/schemas/message_enum_address_retention'
                  description: Determines if the address can be stored or obfuscated
                    based on privacy settings
                SmartEncoded:
                  type: boolean
                  description: 'Whether to detect Unicode characters that have a similar
                    GSM-7 character and replace them. Can be: `true` or `false`.'
                PersistentAction:
                  type: array
                  items:
                    type: string
                  description: Rich actions for non-SMS/MMS channels. Used for [sending
                    location in WhatsApp messages](https://www.twilio.com/docs/whatsapp/message-features#location-messages-with-whatsapp).
                ShortenUrls:
                  type: boolean
                  description: 'For Messaging Services with [Link Shortening configured](https://www.twilio.com/docs/messaging/features/link-shortening)
                    only: A Boolean indicating whether or not Twilio should shorten
                    links in the `body` of the Message. Default value is `false`.
                    If `true`, the `messaging_service_sid` parameter must also be
                    provided.'
                ScheduleType:
                  type: string
                  $ref: '#/components/schemas/message_enum_schedule_type'
                  description: 'For Messaging Services only: Include this parameter
                    with a value of `fixed` in conjuction with the `send_time` parameter
                    in order to [schedule a Message](https://www.twilio.com/docs/messaging/features/message-scheduling).'
                SendAt:
                  type: string
                  format: date-time
                  description: The time that Twilio will send the message. Must be
                    in ISO 8601 format.
                SendAsMms:
                  type: boolean
                  description: If set to `true`, Twilio delivers the message as a
                    single MMS message, regardless of the presence of media.
                ContentVariables:
                  type: string
                  description: 'For [Content Editor/API](https://www.twilio.com/docs/content)
                    only: Key-value pairs of [Template variables](https://www.twilio.com/docs/content/using-variables-with-content-api)
                    and their substitution values. `content_sid` parameter must also
                    be provided. If values are not defined in the `content_variables`
                    parameter, the [Template''s default placeholder values](https://www.twilio.com/docs/content/content-api-resources#create-templates)
                    are used.'
                RiskCheck:
                  type: string
                  $ref: '#/components/schemas/message_enum_risk_check'
                  description: Include this parameter with a value of `disable` to
                    skip any kind of risk check on the respective message request.
                From:
                  type: string
                  format: phone-number
                  description: The sender's Twilio phone number (in [E.164](https://en.wikipedia.org/wiki/E.164)
                    format), [alphanumeric sender ID](https://www.twilio.com/docs/sms/quickstart),
                    [Wireless SIM](https://www.twilio.com/docs/iot/wireless/programmable-wireless-send-machine-machine-sms-commands),
                    [short code](https://www.twilio.com/en-us/messaging/channels/sms/short-codes),
                    or [channel address](https://www.twilio.com/docs/messaging/channels)
                    (e.g., `whatsapp:+15554449999`). The value of the `from` parameter
                    must be a sender that is hosted within Twilio and belongs to the
                    Account creating the Message. If you are using `messaging_service_sid`,
                    this parameter can be empty (Twilio assigns a `from` value from
                    the Messaging Service's Sender Pool) or you can provide a specific
                    sender from your Sender Pool.
                MessagingServiceSid:
                  type: string
                  minLength: 34
                  maxLength: 34
                  pattern: ^MG[0-9a-fA-F]{32}$
                  description: The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/services)
                    you want to associate with the Message. When this parameter is
                    provided and the `from` parameter is omitted, Twilio selects the
                    optimal sender from the Messaging Service's Sender Pool. You may
                    also provide a `from` parameter if you want to use a specific
                    Sender from the Sender Pool.
                Body:
                  type: string
                  description: 'The text content of the outgoing message. Can be up
                    to 1,600 characters in length. SMS only: If the `body` contains
                    more than 160 [GSM-7](https://www.twilio.com/docs/glossary/what-is-gsm-7-character-encoding)
                    characters (or 70 [UCS-2](https://www.twilio.com/docs/glossary/what-is-ucs-2-character-encoding)
                    characters), the message is segmented and charged accordingly.
                    For long `body` text, consider using the [send_as_mms parameter](https://www.twilio.com/blog/mms-for-long-text-messages).'
                MediaUrl:
                  type: array
                  items:
                    type: string
                    format: uri
                  description: The URL of media to include in the Message content.
                    `jpeg`, `jpg`, `gif`, and `png` file types are fully supported
                    by Twilio and content is formatted for delivery on destination
                    devices. The media size limit is 5 MB for supported file types
                    (`jpeg`, `jpg`, `png`, `gif`) and 500 KB for [other types](https://www.twilio.com/docs/messaging/guides/accepted-mime-types)
                    of accepted media. To send more than one image in the message,
                    provide multiple `media_url` parameters in the POST request. You
                    can include up to ten `media_url` parameters per message. [International](https://support.twilio.com/hc/en-us/articles/223179808-Sending-and-receiving-MMS-messages)
                    and [carrier](https://support.twilio.com/hc/en-us/articles/223133707-Is-MMS-supported-for-all-carriers-in-US-and-Canada-)
                    limits apply.
                ContentSid:
                  type: string
                  minLength: 34
                  maxLength: 34
                  pattern: ^HX[0-9a-fA-F]{32}$
                  description: 'For [Content Editor/API](https://www.twilio.com/docs/content)
                    only: The SID of the Content Template to be used with the Message,
                    e.g., `HXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`. If this parameter is not
                    provided, a Content Template is not used. Find the SID in the
                    Console on the Content Editor page. For Content API users, the
                    SID is found in Twilio''s response when [creating the Template](https://www.twilio.com/docs/content/content-api-resources#create-templates)
                    or by [fetching your Templates](https://www.twilio.com/docs/content/content-api-resources#fetch-all-content-resources).'
              required:
              - To
            examples:
              create:
                value:
                  ApplicationSid: APaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                  Body: "Hello! \U0001F44D"
                  From: '+14155552345'
                  MediaUrl:
                  - https://c1.staticflickr.com/3/2899/14341091933_1e92e62d12_b.jpg
                  PersistentAction:
                  - mailto:test@example.com
                  StatusCallback: https://example.com
                  To: '+14155552345'
                  Tags: '{"campaign_name": "Spring Sale 2022","message_type": "cart_abandoned"}'
              createWoService:
                value:
                  ApplicationSid: APaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                  Body: "Hello! \U0001F44D"
                  From: '+14155552345'
                  MediaUrl:
                  - https://example.com
                  PersistentAction:
                  - mailto:test@example.com
                  StatusCallback: https://example.com
                  To: '+14155552345'
              createWithMessagingService:
                value:
                  ApplicationSid: APaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                  Body: "Hello! \U0001F44D"
                  MessagingServiceSid: MGaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                  MediaUrl:
                  - https://example.com
                  PersistentAction:
                  - mailto:test@example.com
                  StatusCallback: https://example.com
                  To: '+14155552345'
                  ContentSid: HXaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
              createWithQueuedStatus:
                value:
                  ApplicationSid: APaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                  Body: "Hello! \U0001F44D"
                  From: '+14155552345'
                  MediaUrl:
                  - https://example.com
                  PersistentAction:
                  - mailto:test@example.com
                  StatusCallback: https://example.com
                  To: '+14155552345'
              createScheduledMessageSms:
                value:
                  Body: "Hello! \U0001F44D"
                  MessagingServiceSid: MGaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                  ScheduleType: fixed
                  StatusCallback: https://example.com
                  To: '+15558675310'
              createScheduledMessageMms:
                value:
                  Body: "Hello! \U0001F44D"
                  MediaUrl:
                  - https://example.com
                  MessagingServiceSid: MGaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                  ScheduleType: fixed
                  StatusCallback: https://example.com
                  To: '+15558675310'
              createScheduledMessageWhatsapp:
                value:
                  Body: "Hello! \U0001F44D"
                  MessagingServiceSid: MGaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                  ScheduleType: fixed
                  StatusCallback: https://example.com
                  To: 94287277+15558675310
      x-twilio:
        conditional:
        - - from
          - messaging_service_sid
        - - body
          - media_url
          - content_sid
    get:
      description: Retrieve a list of Message resources associated with a Twilio Account
      tags:
      - Api20100401Message
      parameters:
      - name: AccountSid
        in: path
        description: The SID of the [Account](https://www.twilio.com/docs/iam/api/account)
          associated with the Message resources.
        schema:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
        required: true
      - name: To
        in: query
        description: 'Filter by recipient. For example: Set this `to` parameter to
          `+15558881111` to retrieve a list of Message resources with `to` properties
          of `+15558881111`'
        schema:
          type: string
          format: phone-number
        x-twilio:
          pii:
            handling: standard
            deleteSla: 120
        examples:
          readFullPage1:
            value: '+123456789'
          readEmptySentdateLess:
            value: '+123456789'
          readEmptySentdateEquals:
            value: '+123456789'
          readEmptySentdateGreater:
            value: '+123456789'
          readEmptySentdateGreaterFormat1:
            value: '+123456789'
          readEmptySentdateGreaterFormat2:
            value: '+123456789'
          readEmptySentdateGreaterFormat3:
            value: '+123456789'
      - name: From
        in: query
        description: 'Filter by sender. For example: Set this `from` parameter to
          `+15552229999` to retrieve a list of Message resources with `from` properties
          of `+15552229999`'
        schema:
          type: string
          format: phone-number
        x-twilio:
          pii:
            handling: standard
            deleteSla: 120
        examples:
          readFullPage1:
            value: '+987654321'
          readEmptySentdateLess:
            value: '+987654321'
          readEmptySentdateEquals:
            value: '+987654321'
          readEmptySentdateGreater:
            value: '+987654321'
          readEmptySentdateGreaterFormat1:
            value: '+987654321'
          readEmptySentdateGreaterFormat2:
            value: '+987654321'
          readEmptySentdateGreaterFormat3:
            value: '+987654321'
      - name: DateSent
        in: query
        description: 'Filter by Message `sent_date`. Accepts GMT dates in the following
          formats: `YYYY-MM-DD` (to find Messages with a specific `sent_date`), `<=YYYY-MM-DD`
          (to find Messages with `sent_date`s on and before a specific date), and
          `>=YYYY-MM-DD` (to find Messages with `sent_dates` on and after a specific
          date).'
        schema:
          type: string
          format: date-time
        examples:
          readEmptySentdateEquals:
            value: '2008-01-02'
      - name: DateSent<
        in: query
        description: 'Filter by Message `sent_date`. Accepts GMT dates in the following
          formats: `YYYY-MM-DD` (to find Messages with a specific `sent_date`), `<=YYYY-MM-DD`
          (to find Messages with `sent_date`s on and before a specific date), and
          `>=YYYY-MM-DD` (to find Messages with `sent_dates` on and after a specific
          date).'
        schema:
          type: string
          format: date-time
        examples:
          readEmptySentdateLess:
            value: '2008-01-02'
      - name: DateSent>
        in: query
        description: 'Filter by Message `sent_date`. Accepts GMT dates in the following
          formats: `YYYY-MM-DD` (to find Messages with a specific `sent_date`), `<=YYYY-MM-DD`
          (to find Messages with `sent_date`s on and before a specific date), and
          `>=YYYY-MM-DD` (to find Messages with `sent_dates` on and after a specific
          date).'
        schema:
          type: string
          format: date-time
        examples:
          readFullPage1:
            value: '2008-01-02'
          readEmptySentdateGreater:
            value: '2008-01-02'
          readEmptySentdateGreaterFormat1:
            value: 06/11/2019 22:05:25 MST
          readEmptySentdateGreaterFormat2:
            value: '2019-06-11 22:05:25.000'
          readEmptySentdateGreaterFormat3:
            value: Wed, 19 Jun 2019 22:04:00 -0000
      - name: PageSize
        in: query
        description: How many resources to return in each list page. The default is
          50, and the maximum is 1000.
        schema:
          type: integer
          minimum: 1
          maximum: 1000
      - name: Page
        in: query
        description: The page index. This value is simply for client state.
        schema:
          type: integer
          minimum: 0
      - name: PageToken
        in: query
        description: The page token. This is provided by the API.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                title: ListMessageResponse
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/api.v2010.account.message'
                  end:
                    type: integer
                  first_page_uri:
                    format: uri
                    type: string
                  next_page_uri:
                    format: uri
                    nullable: true
                    type: string
                  page:
                    type: integer
                  page_size:
                    type: integer
                  previous_page_uri:
                    format: uri
                    nullable: true
                    type: string
                  start:
                    type: integer
                  uri:
                    format: uri
                    type: string
              examples:
                readFullPage1:
                  value:
                    end: 1
                    first_page_uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages.json?To=%2B123456789&From=%2B987654321&DateSent%3E=2008-01-02&PageSize=2&Page=0
                    next_page_uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages.json?To=%2B123456789&From=%2B987654321&DateSent%3E=2008-01-02&PageSize=2&Page=1&PageToken=PAMMc26223853f8c46b4ab7dfaa6abba0a26
                    page: 0
                    page_size: 2
                    previous_page_uri: null
                    messages:
                    - account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      api_version: '2010-04-01'
                      body: testing
                      date_created: Fri, 24 May 2019 17:44:46 +0000
                      date_sent: Fri, 24 May 2019 17:44:50 +0000
                      date_updated: Fri, 24 May 2019 17:44:50 +0000
                      direction: outbound-api
                      error_code: null
                      error_message: null
                      from: '+12019235161'
                      messaging_service_sid: MGaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      num_media: '0'
                      num_segments: '1'
                      price: '-0.00750'
                      price_unit: USD
                      sid: SMded05904ccb347238880ca9264e8fe1c
                      status: sent
                      subresource_uris:
                        media: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/SMded05904ccb347238880ca9264e8fe1c/Media.json
                        feedback: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/SMded05904ccb347238880ca9264e8fe1c/Feedback.json
                      tags:
                        campaign_name: Spring Sale 2022
                        message_type: cart_abandoned
                      to: '+18182008801'
                      uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/SMded05904ccb347238880ca9264e8fe1c.json
                    - account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      api_version: '2010-04-01'
                      body: look mom I have media!
                      date_created: Fri, 24 May 2019 17:44:46 +0000
                      date_sent: Fri, 24 May 2019 17:44:49 +0000
                      date_updated: Fri, 24 May 2019 17:44:49 +0000
                      direction: inbound
                      error_code: 30004
                      error_message: Message blocked
                      from: '+12019235161'
                      messaging_service_sid: MGaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                      num_media: '3'
                      num_segments: '1'
                      price: '-0.00750'
                      price_unit: USD
                      sid: MMc26223853f8c46b4ab7dfaa6abba0a26
                      status: received
                      subresource_uris:
                        media: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/MMc26223853f8c46b4ab7dfaa6abba0a26/Media.json
                        feedback: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/MMc26223853f8c46b4ab7dfaa6abba0a26/Feedback.json
                      tags:
                        campaign_name: Spring Sale 2022
                        message_type: cart_abandoned
                      to: '+18182008801'
                      uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages/MMc26223853f8c46b4ab7dfaa6abba0a26.json
                    start: 0
                    uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages.json?To=%2B123456789&From=%2B987654321&DateSent%3E=2008-01-02&PageSize=2&Page=0
                readEmptySentdateLess:
                  value:
                    end: 0
                    first_page_uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages.json?To=%2B123456789&From=%2B987654321&DateSent%3C=2008-01-02&PageSize=25&Page=0
                    next_page_uri: null
                    page: 0
                    page_size: 25
                    previous_page_uri: null
                    messages: []
                    start: 0
                    uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages.json?To=%2B123456789&From=%2B987654321&DateSent%3C=2008-01-02&PageSize=25&Page=0
                readEmptySentdateEquals:
                  value:
                    end: 0
                    first_page_uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages.json?To=%2B123456789&From=%2B987654321&DateSent=2008-01-02&PageSize=25&Page=0
                    next_page_uri: null
                    page: 0
                    page_size: 25
                    previous_page_uri: null
                    messages: []
                    start: 0
                    uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages.json?To=%2B123456789&From=%2B987654321&DateSent=2008-01-02&PageSize=25&Page=0
                readEmptySentdateGreater:
                  value:
                    end: 0
                    first_page_uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages.json?To=%2B123456789&From=%2B987654321&DateSent%3E=2008-01-02&PageSize=25&Page=0
                    next_page_uri: null
                    page: 0
                    page_size: 25
                    previous_page_uri: null
                    messages: []
                    start: 0
                    uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages.json?To=%2B123456789&From=%2B987654321&DateSent%3E=2008-01-02&PageSize=25&Page=0
                readEmptySentdateGreaterFormat1:
                  value:
                    end: 0
                    first_page_uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages.json?To=%2B123456789&From=%2B987654321&DateSent%3E=06%2F11%2F2019+22%3A05%3A25+MST&PageSize=25&Page=0
                    next_page_uri: null
                    page: 0
                    page_size: 25
                    previous_page_uri: null
                    messages: []
                    start: 0
                    uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages.json?To=%2B123456789&From=%2B987654321&DateSent%3E=06%2F11%2F2019+22%3A05%3A25+MST&PageSize=25&Page=0
                readEmptySentdateGreaterFormat2:
                  value:
                    end: 0
                    first_page_uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages.json?To=%2B123456789&From=%2B987654321&DateSent%3E=2019-06-11+22%3A05%3A25.000&PageSize=25&Page=0
                    next_page_uri: null
                    page: 0
                    page_size: 25
                    previous_page_uri: null
                    messages: []
                    start: 0
                    uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages.json?To=%2B123456789&From=%2B987654321&DateSent%3E=2019-06-11+22%3A05%3A25.000&PageSize=25&Page=0
                readEmptySentdateGreaterFormat3:
                  value:
                    end: 0
                    first_page_uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages.json?To=%2B123456789&From=%2B987654321&DateSent%3E=Wed%2C+19+Jun+2019+22%3A04%3A00+-0000&PageSize=25&Page=0
                    next_page_uri: null
                    page: 0
                    page_size: 25
                    previous_page_uri: null
                    messages: []
                    start: 0
                    uri: /2010-04-01/Accounts/ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Messages.json?To=%2B123456789&From=%2B987654321&DateSent%3E=Wed%2C+19+Jun+2019+22%3A04%3A00+-0000&PageSize=25&Page=0
          headers:
            Access-Control-Allow-Origin:
              description: Specify the origin(s) allowed to access the resource
              schema:
                type: string
              example: '*'
            Access-Control-Allow-Methods:
              description: Specify the HTTP methods allowed when accessing the resource
              schema:
                type: string
              example: POST, OPTIONS
            Access-Control-Allow-Headers:
              description: Specify the headers allowed when accessing the resource
              schema:
                type: string
              example: Content-Type, Authorization
            Access-Control-Allow-Credentials:
              description: Indicates whether the browser should include credentials
              schema:
                type: boolean
            Access-Control-Expose-Headers:
              description: Headers exposed to the client
              schema:
                type: string
                example: X-Custom-Header1, X-Custom-Header2
          description: OK
      security:
      - accountSid_authToken: []
      operationId: ListMessage
servers:
- url: https://api.twilio.com
tags:
- name: Api20100401Account
- name: Api20100401AddOnResult
- name: Api20100401Address
- name: Api20100401AllTime
- name: Api20100401Application
- name: Api20100401AssignedAddOn
- name: Api20100401AssignedAddOnExtension
- name: Api20100401AuthCallsCredentialListMapping
- name: Api20100401AuthCallsIpAccessControlListMapping
- name: Api20100401AuthRegistrationsCredentialListMapping
- name: Api20100401AuthorizedConnectApp
- name: Api20100401AvailablePhoneNumberCountry
- name: Api20100401Balance
- name: Api20100401Call
- name: Api20100401Conference
- name: Api20100401ConnectApp
- name: Api20100401Credential
- name: Api20100401CredentialList
- name: Api20100401CredentialListMapping
- name: Api20100401Daily
- name: Api20100401Data
- name: Api20100401DependentPhoneNumber
- name: Api20100401Domain
- name: Api20100401Event
- name: Api20100401Feedback
- name: Api20100401HealthCheck
- name: Api20100401IncomingPhoneNumber
- name: Api20100401IpAccessControlList
- name: Api20100401IpAccessControlListMapping
- name: Api20100401IpAddress
- name: Api20100401Key
- name: Api20100401LastMonth
- name: Api20100401Local
- name: Api20100401MachineToMachine
- name: Api20100401Media
- name: Api20100401Member
- name: Api20100401Message
- name: Api20100401Mobile
- name: Api20100401Monthly
- name: Api20100401National
- name: Api20100401NewKey
- name: Api20100401NewSigningKey
- name: Api20100401Notification
- name: Api20100401OutgoingCallerId
- name: Api20100401Participant
- name: Api20100401Payload
- name: Api20100401Payment
- name: Api20100401Queue
- name: Api20100401Record
- name: Api20100401Recording
- name: Api20100401Region
- name: Api20100401SharedCost
- name: Api20100401ShortCode
- name: Api20100401SigningKey
- name: Api20100401Sip
- name: Api20100401Siprec
- name: Api20100401SmsMessage
- name: Api20100401Stream
- name: Api20100401ThisMonth
- name: Api20100401Today
- name: Api20100401Token
- name: Api20100401TollFree
- name: Api20100401Transcription
- name: Api20100401Trigger
- name: Api20100401TypeParameterized
- name: Api20100401UserDefinedMessage
- name: Api20100401UserDefinedMessageSubscription
- name: Api20100401ValidationRequest
- name: Api20100401Voip
- name: Api20100401Yearly
- name: Api20100401Yesterday
security:
- accountSid_authToken: []
